### ISSUE TITLE
collada model doesn't appear while using the Index.html file in Glitch

### ISSUE THREAD

**Issue by addy1997** [gftruj/webzamples#3]
Hi @gftruj,

Firstly, this is a fantastic repository and very useful for beginners with A-frame. I am trying to simulate the elf and the stormtrooper files using the frame on Glitch.

I've included the directory structure below. I placed all the 3D model files and images in the **assets** directory.
![Screenshot 2023-02-08 at 17 58 08](https://user-images.githubusercontent.com/29406906/217613289-d8ec0976-08b2-4362-a7a9-a2f68034ea0e.png)

The output I get is this

![Screenshot 2023-02-08 at 17 59 54](https://user-images.githubusercontent.com/29406906/217613696-761e3071-299f-4561-8754-30366403a458.png)

Could you suggest something?

Thanks

**Comment by gftruj** [comment]
Hi, looks like it was out of date (either the three loader, or my usage for aframe 1.2.0).
I've updated the `collada-model` so it uses the 'newest' THREE.ColladaLoader, and the component.
It [seems to be working](https://gftruj.github.io/webzamples/aframe/collada/), but it reports a warning[ (looks like it's intentional tho)](https://github.com/mrdoob/three.js/issues/24289#issuecomment-1177058748).
Let me know if it's working for you as well,

Thanks a lot for reporting an issue btw!
Cheers

**Comment by addy1997** [comment]
> Hi, looks like it was out of date (either the three loader, or my usage for aframe 1.2.0). I've updated the `collada-model` so it uses the 'newest' THREE.ColladaLoader, and the component. It [seems to be working](https://gftruj.github.io/webzamples/aframe/collada/), but it reports a warning[ (looks like it's intentional tho)](https://github.com/mrdoob/three.js/issues/24289#issuecomment-1177058748). Let me know if it's working for you as well,
> 
> Thanks a lot for reporting an issue btw! Cheers

Thanks for your response. This seems to work properly on [JSFiddle](https://jsfiddle.net/adwait3301/azrnqbmj/36/). However, I've not tested it locally on my machine.
