### ISSUE TITLE
Message: Cross-Origin Read Blocking (CORB) blocked cross-origin response

### ISSUE THREAD

**Issue by addy1997** [gftruj/webzamples#5]
Hi @gftruj,

I am trying to replicate your [bounding box](https://github.com/gftruj/webzamples/blob/master/aframe/models/bounding_boxes.html) example. The browser I am using is Mozilla Firefox (latest version).

My aim is to load the stormtrooper.dae model, which I am not able to load due to the warning message shown below:

ERROR1: `device:error WebXR session support error: Failed to execute 'isSessionSupported' on 'XRSystem': Access to the feature "xr" is disallowed by permissions policy.`

ERROR2:` Cross-Origin Read Blocking (CORB) blocked cross-origin response`

The code is available [here](https://jsfiddle.net/adwait3301/ybupx53m/34/) to try.

Could you recommend anything?

Thanks,
Adwait

**Comment by gftruj** [comment]
Sorry for the late response, just found out that my stuff broke between 1.0.4 - 1.4.0, did you manage to make it work? 
I'll look into it this week.

**Comment by addy1997** [comment]
Sorry for posting a broken link to the code. Not yet, but I am trying to make it work. I just wanted to ask, how did you come up with [this](https://raw.githubusercontent.com/gftruj/webzamples/master/aframe/collada/dist/collada-model.js) component?

**Comment by addy1997** [comment]
Hi @gftruj 
Sorry for posting a broken link to the code. Not yet, but I am trying to make it work. I just wanted to ask, how did you come up with [this](https://raw.githubusercontent.com/gftruj/webzamples/master/aframe/collada/dist/collada-model.js) component? Can I write one for the FBX loader?

**Comment by addy1997** [comment]
Hi @gftruj,

Sorry to bother you. Would you be able to help or should I close the issue?

**Comment by gftruj** [comment]
@addy1997 sure, I'll try to help, though I'm having some time trouble :)
the collada model component is just an export of the threejs collada loader.

As for the fbx one, for whatever reason (the fileloader returning strings instead of arraybuffers) i was unable to use the threejs fbx loader with a simple export. After a fierce battle i came up with something ([fbx loader example](https://gftruj.github.io/webzamples/aframe/fbx/examples/fbx.html) - watch out, big filesizes). Works well with the fbx model from the threejs repo, but the textures seem to be messed up when used on a sketchfab model.

I'll try to check out whats happening with the boxes this week.

**Comment by gftruj** [comment]
Managed to fix (make it work with aframe 1.4.0) the [bounding boxes](https://gftruj.github.io/webzamples/aframe/models/bounding_boxes.html) example, but using my custom "bone position calculation" instead of the native `applyBoneTransform`. Not sure why yet. Also i've added the collada and fbx model there and the FPS went pretty low, i think the models should be toggled, not all at once 😅

**Comment by addy1997** [comment]
> @addy1997 sure, I'll try to help, though I'm having some time trouble :) the collada model component is just an export of the threejs collada loader.
> 
> As for the fbx one, for whatever reason (the fileloader returning strings instead of arraybuffers) i was unable to use the threejs fbx loader with a simple export. After a fierce battle i came up with something ([fbx loader example](https://gftruj.github.io/webzamples/aframe/fbx/examples/fbx.html) - watch out, big filesizes). Works well with the fbx model from the threejs repo, but the textures seem to be messed up when used on a sketchfab model.
> 
> I'll try to check out whats happening with the boxes this week.

Sorry for late reply. Thanks you so much @gftruj.
